# Generated by Django 5.2.9 on 2025-12-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Appeal',
        ),
    ]
