# Generated by Django 5.2.9 on 2025-12-05 19:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0004_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Message',
        ),
    ]
