# Generated by Django 5.2.9 on 2025-12-05 19:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0005_rename_question_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='BeneficiaryMessage',
        ),
    ]
