# Generated by Django 5.2.9 on 2025-12-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0008_message_delete_beneficiarymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('donated', 'Donated')], default='pending', max_length=20),
        ),
    ]
