# Generated by Django 5.2.9 on 2025-12-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0009_appeal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
