# Generated by Django 5.2.9 on 2025-12-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0010_appeal_is_authorized_profile_is_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('donated', 'Donated'), ('authorized', 'Authorized')], default='pending', max_length=20),
        ),
    ]
