# Generated by Django 5.2.9 on 2025-12-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0011_alter_appeal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='name',
        ),
    ]
