# Generated by Django 5.2.9 on 2025-12-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0012_remove_appeal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='Email',
        ),
    ]
